### PR TITLE
Frequent upload of repositories (actually every 10 min)

### PR DESCRIPTION
**Pull request by asere**
Hello,
So this PR should make the instances able to upload their repositories at a frequent time (every 10 min).
This should help keeping the last changes even when the instance is online for a long time (like a month).

### CODE REVIEW

**Comment by yurug** [comment]
Please apply [`shellcheck`](https://www.shellcheck.net/) to your script shells to improve their quality.

**Comment by asere** [comment]
> Please apply [`shellcheck`](https://www.shellcheck.net/) to your script shells to improve their quality.

done

**Comment by yurug** [comment]
Please add shellcheck in the CI.

**Comment by asere** [comment]
should be added with PR #10

**Pull request merged**
