### PR TITLE
adding CI for shellcheck

### PR DESCRIPTION
**Pull request by asere**
This PR adds a continuous use of `shellcheck` on `program.sh` at every pull request.

### CODE REVIEW

**Comment by asere** [comment]
@yurug can you review this PR and PR #8 ? The frequent upload feature is really needed to prevent data loss from random resets issue.

**Comment by yurug** [comment]
Let's see if that works!

**Comment by asere** [comment]
@yurug here is a little test where the workflow should fail on my fork asere#2.

**Comment by yurug** [comment]
Cool! Thanks!

**Pull request merged**
